/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.ProdutoData;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;

/**
 *
 * @author PC
 */
public class JFCadProduto extends javax.swing.JInternalFrame {
    
    private Produto objProduto;
    private ProdutoData DAO;
    private ArrayList<Produto> listaDeProdutos;
    int acao = 0;
    /**
     * Creates new form JFCadProduto
     */
    public JFCadProduto() {
        initComponents();
        objProduto = new Produto();
        listaDeProdutos = new ArrayList<>();
                
        ActionEvent evt = null;                
        jbCancelarProdutoActionPerformed(evt);
        
        try {
            DAO = new ProdutoData();
        } catch (Exception ex) {
            Logger.getLogger(JFCadCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlId = new javax.swing.JLabel();
        jlIdProduto = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jlCusto = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfCusto = new javax.swing.JTextField();
        jlQuantidade = new javax.swing.JLabel();
        jtfQuantidade = new javax.swing.JTextField();
        jbNovoProduto = new javax.swing.JButton();
        jbCancelarProduto = new javax.swing.JButton();
        jbExcluirProduto = new javax.swing.JButton();
        jlPesquisa = new javax.swing.JLabel();
        jtfPesquisaProduto = new javax.swing.JTextField();
        jspProduto = new javax.swing.JScrollPane();
        jtProduto = new javax.swing.JTable();
        jbSalvarProduto = new javax.swing.JButton();
        jbEditarProduto = new javax.swing.JButton();

        setClosable(true);
        setTitle("Produto");

        jlId.setText("ID");

        jlIdProduto.setText("0");

        jlNome.setText("Nome");

        jlCusto.setText("Custo");

        jtfNome.setEnabled(false);
        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });

        jtfCusto.setEnabled(false);
        jtfCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCustoActionPerformed(evt);
            }
        });

        jlQuantidade.setText("Quantidade");

        jtfQuantidade.setEnabled(false);

        jbNovoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus_32.png"))); // NOI18N
        jbNovoProduto.setText("Novo");
        jbNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoProdutoActionPerformed(evt);
            }
        });

        jbCancelarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/block_32.png"))); // NOI18N
        jbCancelarProduto.setText("Cancelar");
        jbCancelarProduto.setEnabled(false);
        jbCancelarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarProdutoActionPerformed(evt);
            }
        });

        jbExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_32.png"))); // NOI18N
        jbExcluirProduto.setText("Excluir");
        jbExcluirProduto.setEnabled(false);
        jbExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirProdutoActionPerformed(evt);
            }
        });

        jlPesquisa.setText("Pesquisa");

        jtfPesquisaProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisaProdutoKeyReleased(evt);
            }
        });

        jtProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nome", "Custo", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProdutoMouseClicked(evt);
            }
        });
        jspProduto.setViewportView(jtProduto);
        if (jtProduto.getColumnModel().getColumnCount() > 0) {
            jtProduto.getColumnModel().getColumn(0).setPreferredWidth(1);
            jtProduto.getColumnModel().getColumn(2).setPreferredWidth(1);
            jtProduto.getColumnModel().getColumn(3).setPreferredWidth(1);
        }

        jbSalvarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick_32.png"))); // NOI18N
        jbSalvarProduto.setText("Salvar");
        jbSalvarProduto.setEnabled(false);
        jbSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarProdutoActionPerformed(evt);
            }
        });

        jbEditarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil_32.png"))); // NOI18N
        jbEditarProduto.setText("Editar");
        jbEditarProduto.setEnabled(false);
        jbEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jspProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlNome)
                                        .addGap(45, 45, 45)
                                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlQuantidade)
                                            .addComponent(jlCusto))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jbNovoProduto)
                                .addGap(18, 18, 18)
                                .addComponent(jbEditarProduto)
                                .addGap(18, 18, 18)
                                .addComponent(jbExcluirProduto))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlId)
                                .addGap(67, 67, 67)
                                .addComponent(jlIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlPesquisa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbSalvarProduto)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbCancelarProduto)))))
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlId)
                    .addComponent(jlIdProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCusto))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQuantidade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEditarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPesquisa)
                    .addComponent(jtfPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jspProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeActionPerformed

    private void jbNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoProdutoActionPerformed
        jtfNome.setEnabled(true);
        jtfCusto.setEnabled(true);
        jtfQuantidade.setEnabled(true);
        
        jbNovoProduto.setEnabled(false);
        jbExcluirProduto.setEnabled(false);
        jbEditarProduto.setEnabled(false);        
        jbCancelarProduto.setEnabled(true);
        jbSalvarProduto.setEnabled(true);
        
        jtProduto.setEnabled(false);
        jtfPesquisaProduto.setEnabled(false);
        
        jtfNome.setText("");
        jtfCusto.setText("");
        jtfQuantidade.setText("");
        
        acao = 1;
    }//GEN-LAST:event_jbNovoProdutoActionPerformed

    private void jbCancelarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarProdutoActionPerformed
        jbNovoProduto.setEnabled(true);
        jbSalvarProduto.setEnabled(false);
        jbCancelarProduto.setEnabled(false);
        jbEditarProduto.setEnabled(false);
        jbExcluirProduto.setEnabled(false);
        jtfPesquisaProduto.setEnabled(true);
        jtProduto.setEnabled(true);
        jtfNome.setEnabled(false);
        jtfCusto.setEnabled(false);
        jtfQuantidade.setEnabled(false);
        jtfNome.setText("");
        jtfCusto.setText("");
        jtfQuantidade.setText("");
    }//GEN-LAST:event_jbCancelarProdutoActionPerformed

    private void jbExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirProdutoActionPerformed
       try {
            if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o registro?") == JOptionPane.YES_OPTION) {
                if (DAO.excluir(Integer.parseInt(jlIdProduto.getText()))) {
                    JOptionPane.showMessageDialog(this, "Excluído.");
                    jbCancelarProdutoActionPerformed(evt);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
        }
    }//GEN-LAST:event_jbExcluirProdutoActionPerformed

    private void jbSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarProdutoActionPerformed
        try {
            if (validarCampos()) {
                
                if (preencherObjeto()) {
                    
                    if (acao == 1) {
                        if (DAO.incluir(objProduto)) {
                            JOptionPane.showMessageDialog(this, "Salvo com sucesso!",
                                    "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                            //salvar no banco
                            jbCancelarProdutoActionPerformed(evt);
                        }
                    }
                    if (acao == 2) {
                        if (DAO.editar(objProduto)) {
                            JOptionPane.showMessageDialog(this, "Editado com sucesso!",
                                    "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                            //salvar no banco
                            jbCancelarProdutoActionPerformed(evt);
                        }
                    }
                }
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar:" + erro.getMessage(), "Sistema", JOptionPane.ERROR_MESSAGE);

        }
     
    }//GEN-LAST:event_jbSalvarProdutoActionPerformed

    private void jbEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarProdutoActionPerformed
        acao = 2; //editar
        jtfNome.setEnabled(true);
        jtfCusto.setEnabled(true);
        jtfQuantidade.setEnabled(true);        
        
        jbSalvarProduto.setEnabled(true);
        jbCancelarProduto.setEnabled(true);
        
        jbNovoProduto.setEnabled(false);
        jbEditarProduto.setEnabled(false);
        jbExcluirProduto.setEnabled(false);

    }//GEN-LAST:event_jbEditarProdutoActionPerformed

    private void jtfPesquisaProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaProdutoKeyReleased
    try {
            listaDeProdutos = DAO.pesquisar(jtfPesquisaProduto.getText());
            DefaultTableModel mp = (DefaultTableModel) jtProduto.getModel();
            mp.setNumRows(0);
        for (Produto u : listaDeProdutos) {
            mp.addRow(new String[]{"" + u.getIdProduto(), u.getNomeProduto(),"" + u.getCustoProduto(),"" +  u.getQtdProduto()}); //,u.getCustoProduto(), u.getQtdProduto()
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar:" + e.getMessage());
        }
    }//GEN-LAST:event_jtfPesquisaProdutoKeyReleased

    private void jtfCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCustoActionPerformed

    private void jtProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProdutoMouseClicked
    int linhaSelecionada = jtProduto.getSelectedRow();
        if (linhaSelecionada > -1) {
            jlIdProduto.setText("" + listaDeProdutos.get(linhaSelecionada).getIdProduto());
            jtfNome.setText("" + listaDeProdutos.get(linhaSelecionada).getNomeProduto());
            jtfCusto.setText("" + listaDeProdutos.get(linhaSelecionada).getCustoProduto());
            jtfQuantidade.setText("" + listaDeProdutos.get(linhaSelecionada).getQtdProduto());
            jbEditarProduto.setEnabled(true);
            jbExcluirProduto.setEnabled(true);
        } else {
            jbEditarProduto.setEnabled(false);
            jbExcluirProduto.setEnabled(false);
        }
    }//GEN-LAST:event_jtProdutoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancelarProduto;
    private javax.swing.JButton jbEditarProduto;
    private javax.swing.JButton jbExcluirProduto;
    private javax.swing.JButton jbNovoProduto;
    private javax.swing.JButton jbSalvarProduto;
    private javax.swing.JLabel jlCusto;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlIdProduto;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlPesquisa;
    private javax.swing.JLabel jlQuantidade;
    private javax.swing.JScrollPane jspProduto;
    private javax.swing.JTable jtProduto;
    private javax.swing.JTextField jtfCusto;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfPesquisaProduto;
    private javax.swing.JTextField jtfQuantidade;
    // End of variables declaration//GEN-END:variables
        private boolean validarCampos() {
            String msg = new String();
            if (jtfNome.getText().trim().length() < 3) {
                msg = "\nVerifique o nome!";
            }
            if (jtfCusto.getText().trim().length() == 0) {
                msg = "\nVerifique o custo!";
            }
            if (jtfQuantidade.getText().trim().length() == 0) {
                msg = "\nVerifique a quantidade!";
            }

            if (msg.isEmpty()) {
                return true;
            } else {
                JOptionPane.showMessageDialog(this, "erros" + msg,"\nValidação", JOptionPane.ERROR_MESSAGE);
                return false;
            }

        }
    
        private boolean preencherObjeto() throws Exception { 
        objProduto.setIdProduto(Integer.parseInt(jlIdProduto.getText()));
        objProduto.setNomeProduto(jtfNome.getText());        
        objProduto.setCustoProduto(Double.parseDouble(jtfCusto.getText()));        
        objProduto.setQtdProduto(Integer.parseInt(jtfQuantidade.getText()));

        return true;
        }

    private void Dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
